AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Api:
    Cors:
      AllowMethods: "'POST,OPTIONS'"
      AllowHeaders: "'Content-Type'"
      AllowOrigin: "'http://localhost:4200'"

Resources:
  EncryptPDFFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: EncryptPDF
      Architectures: [x86_64]
      CodeUri: encrypt_pdf/
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      Timeout: 15
      MemorySize: 256
      LoggingConfig:
        LogFormat: JSON
      Policies:
        - AmazonS3FullAccess
        - AmazonDynamoDBFullAccess
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref PDFSourceBucket
            Events: s3:ObjectCreated:*
  
  GenerateUploadUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GenerateUploadUrl
      Architectures:
        - x86_64
      CodeUri: generate_upload_url/
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      Timeout: 10
      MemorySize: 128
      Policies:
        - AmazonS3FullAccess
        - AmazonDynamoDBFullAccess
      Events:
        UploadApi:
          Type: Api
          Properties:
            Path: /upload-url
            Method: post

  PDFSourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: isuranga-source-bucket-file-encrypter

  EncryptedPDFBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: isuranga-destination-bucket-file-encrypter